In [1]:
import pandas as pd

In [20]:
#read csv file

df=pd.read_csv('students_data.csv')
print(df)

            name  maths  science  english dept
0   Aarav Sharma   85.0       89     75.0  CSE
1     Diya Patel   78.0       82     90.0  ECE
2    Rohan Verma   92.0       94     88.0   ME
3   Ananya Singh   88.0       85     92.0  CSE
4    Karan Mehta   74.0       70     68.0  EEE
5    Sneha Reddy   81.0       88     84.0   IT
6   Ishaan Gupta   95.0       91     79.0  CSE
7     Meera Nair   69.0       73     95.0   CE
8     Aditya Rao   90.0       87     83.0   ME
9      Priya Das   76.0       80     77.0   IT
10          Aids    NaN        9      NaN   IT

In [ ]:
# add new column total
df['total']=df['maths']+df['science']+df['english']

print(df)

           name  maths  science  english dept  total
0  Aarav Sharma     85       89       75  CSE    249
1    Diya Patel     78       82       90  ECE    250
2   Rohan Verma     92       94       88   ME    274
3  Ananya Singh     88       85       92  CSE    265
4   Karan Mehta     74       70       68  EEE    212
5   Sneha Reddy     81       88       84   IT    253
6  Ishaan Gupta     95       91       79  CSE    265
7    Meera Nair     69       73       95   CE    237
8    Aditya Rao     90       87       83   ME    260
9     Priya Das     76       80       77   IT    233

In [ ]:
# add a column average
df['average']=df['total']/3

#print(df)

           name  maths  science  english dept  total    average
0  Aarav Sharma     85       89       75  CSE    249  83.000000
1    Diya Patel     78       82       90  ECE    250  83.333333
2   Rohan Verma     92       94       88   ME    274  91.333333
3  Ananya Singh     88       85       92  CSE    265  88.333333
4   Karan Mehta     74       70       68  EEE    212  70.666667
5   Sneha Reddy     81       88       84   IT    253  84.333333
6  Ishaan Gupta     95       91       79  CSE    265  88.333333
7    Meera Nair     69       73       95   CE    237  79.000000
8    Aditya Rao     90       87       83   ME    260  86.666667
9     Priya Das     76       80       77   IT    233  77.666667

In [ ]:
#top 3 studnets based on total
df.nlargest(3,'total')

           name  maths  science  english dept  total    average
2   Rohan Verma     92       94       88   ME    274  91.333333
3  Ananya Singh     88       85       92  CSE    265  88.333333
6  Ishaan Gupta     95       91       79  CSE    265  88.333333

In [ ]:
#dept wise average marks
df.groupby('dept')['total'].mean()

dept
CE     237.000000
CSE    259.666667
ECE    250.000000
EEE    212.000000
IT     243.000000
ME     267.000000
Name: total, dtype: float64

In [ ]:
#students scoring above 75 in all subjects
filtered_rows=df[(df['maths']>75) & (df['science']>75) & (df['english']>75)]
print(filtered_rows)

           name  maths  science  english dept  total    average
1    Diya Patel     78       82       90  ECE    250  83.333333
2   Rohan Verma     92       94       88   ME    274  91.333333
3  Ananya Singh     88       85       92  CSE    265  88.333333
5   Sneha Reddy     81       88       84   IT    253  84.333333
6  Ishaan Gupta     95       91       79  CSE    265  88.333333
8    Aditya Rao     90       87       83   ME    260  86.666667
9     Priya Das     76       80       77   IT    233  77.666667

In [21]:
df.isnull()

     name  maths  science  english   dept
0   False  False    False    False  False
1   False  False    False    False  False
2   False  False    False    False  False
3   False  False    False    False  False
4   False  False    False    False  False
5   False  False    False    False  False
6   False  False    False    False  False
7   False  False    False    False  False
8   False  False    False    False  False
9   False  False    False    False  False
10  False   True    False     True  False

In [ ]:
#handle missing values
df['maths']=df['maths'].fillna(df['maths'].mean())
df['english']=df['english'].fillna(df['english'].mean())
print(df)

            name  maths  science  english dept
0   Aarav Sharma   85.0       89     75.0  CSE
1     Diya Patel   78.0       82     90.0  ECE
2    Rohan Verma   92.0       94     88.0   ME
3   Ananya Singh   88.0       85     92.0  CSE
4    Karan Mehta   74.0       70     68.0  EEE
5    Sneha Reddy   81.0       88     84.0   IT
6   Ishaan Gupta   95.0       91     79.0  CSE
7     Meera Nair   69.0       73     95.0   CE
8     Aditya Rao   90.0       87     83.0   ME
9      Priya Das   76.0       80     77.0   IT
10          Aids   82.8        9     83.1   IT

# 📘 Pandas Student Data Analysis – Explanation Notes

---

# 1️⃣ Reading the CSV File

```python
import pandas as pd
df = pd.read_csv('students_data.csv')
print(df)
```

## Explanation
- `pd.read_csv()` loads the CSV file into a Pandas DataFrame.
- The DataFrame is a 2D table (rows and columns).
- `print(df)` displays the dataset.

---

# 2️⃣ Adding a New Column – Total Marks

```python
df['total'] = df['maths'] + df['science'] + df['english']
```

## Explanation
- A new column `total` is created.
- It performs **row-wise addition** of three subject columns.
- For each student:

```
total = maths + science + english
```

This updates the DataFrame permanently.

---

# 3️⃣ Adding Average Column

```python
df['average'] = df['total'] / 3
```

## Explanation
- Creates a new column `average`.
- Divides total marks by 3 subjects.
- Formula:

```
average = total / number_of_subjects
```

---

# 4️⃣ Top 3 Students Based on Total

```python
df.nlargest(3, 'total')
```

## Explanation
- `nlargest(n, column)` returns top `n` rows sorted by a column.
- Here it selects top 3 students with highest total marks.
- Efficient and cleaner than sorting + head().

Equivalent to:

```python
df.sort_values(by='total', ascending=False).head(3)
```

---

# 5️⃣ Department-wise Average Total Marks

```python
df.groupby('dept')['total'].mean()
```

## Explanation
- `groupby('dept')` → Groups students by department.
- `['total']` → Selects total marks column.
- `.mean()` → Calculates average total marks per department.

Formula internally:

```
Department Average = Sum of totals in dept / Number of students in dept
```

Returns a Pandas Series indexed by department.

---

# 6️⃣ Students Scoring Above 75 in All Subjects

```python
filtered_rows = df[
    (df['maths'] > 75) & 
    (df['science'] > 75) & 
    (df['english'] > 75)
]
print(filtered_rows)
```

## Explanation
- Each condition creates a True/False column.
- `&` is the AND operator for Pandas.
- Only rows where all conditions are True are selected.
- Parentheses are required for correct evaluation.

Logical Meaning:

```
maths > 75 AND
science > 75 AND
english > 75
```

---

# 7️⃣ Checking Missing Values

```python
df.isnull()
```

## Explanation
- Returns a DataFrame of True/False.
- True → value is missing (NaN).
- False → value exists.
- Used to identify missing data locations.

To count missing values:

```python
df.isnull().sum()
```

---

# 8️⃣ Handling Missing Values (Mean Imputation)

```python
df['maths'] = df['maths'].fillna(df['maths'].mean())
df['english'] = df['english'].fillna(df['english'].mean())
print(df)
```

## Explanation
- `fillna()` replaces missing values.
- `df['maths'].mean()` calculates average ignoring NaN.
- Missing values are replaced with mean of the column.

Why Mean?
- Maintains dataset size
- Preserves approximate distribution
- Common preprocessing method in ML

Mathematically:

```
New Value = (Sum of non-missing values) / (Count of non-missing values)
```

---

# 🔁 Overall Workflow Summary

1. Load dataset
2. Create derived columns (total, average)
3. Rank students (top 3)
4. Perform grouped analysis (dept-wise average)
5. Apply conditional filtering
6. Detect missing values
7. Handle missing values using mean imputation

---

# 🎯 Key Pandas Concepts Used

- `read_csv()` → Load data
- Column arithmetic → Feature engineering
- `nlargest()` → Ranking
- `groupby()` → Aggregation
- Boolean indexing → Filtering
- `isnull()` → Missing value detection
- `fillna()` → Missing value handling

---

# 📌 Core Learning

This workflow demonstrates:
- Data manipulation
- Feature creation
- Aggregation
- Filtering
- Data cleaning

These are foundational steps in data analysis and machine learning preprocessing.