In [ ]:
print(1)

### PANDAS

In [ ]:
'''
WHAT IS PANDAS?

Library which is used for data cleaning , data analysis , data transformation , working with structure data

example: excel automation,data cleaning before ml,sales report , financial analysis , student performance tracking


pandas series:
1D Labeled array like single column in excel

'''

In [ ]:
import pandas as pd

In [ ]:
mark=pd.Series([85,90,78,92])
print(mark)

In [ ]:
mark=pd.Series([85,90,78,92],index=['a','b','c','d'])
print(mark)

In [ ]:
print(mark['c'])
print(mark[1])

In [ ]:
#creating dataframe from dictionary

data={
    "name":['Ravi','Anita','John','Meera'],
    'age':[21,20,22,23],
    'marks':[85,90,78,92]
}

df=pd.DataFrame(data)
print(df)

In [ ]:
print(df['name'])

In [ ]:
print(df[['name','marks']])

In [ ]:
print(df.loc[0]) #by label
print(df.iloc[1]) #by index

In [ ]:
#adding column
df['Result']=df['marks']>80
print(df)

In [ ]:
#deleting
df.drop('age',axis=1,inplace=True)
print(df)

In [18]:
#Reading CSV file
df=pd.read_csv('student.csv')
print(df)

    Name  Math  Science  English
0  Aditi    85       90       80
1   Ravi    78       82       88
2  Meena    92       95       94

In [19]:
pd.read_csv('student.csv',header=0)

    Name  Math  Science  English
0  Aditi    85       90       80
1   Ravi    78       82       88
2  Meena    92       95       94

In [21]:
pd.read_csv('student.csv',nrows=2)

    Name  Math  Science  English
0  Aditi    85       90       80
1   Ravi    78       82       88

In [22]:
pd.read_csv('student.csv',usecols=['Name','Math'])

    Name  Math
0  Aditi    85
1   Ravi    78
2  Meena    92

In [23]:
%pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\aadis\appdata\roaming\python\python313\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\aadis\appdata\roaming\python\python313\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [24]:
df=pd.read_excel('Student.xlsx')
print(df)

        Names  RollNo  AI  DBMS  PP  WP  EMSML
0      Rajesh       1  70    45  43  45     89
1     Mahesh        2  85    56  13  63     78
2      Naresh       3  89    46  46  23     46
3      Suresh       4  92    31  78  15     86
4      Vishnu       5  94    30  23  46     79
5     Pradeep       6  87    89  96  75     36
6      Ramesh       7  84    74  45  14     45
7     Amrutha       8  86    26  78  11     21
8    Sai Teja       9  83    89  69  45     25
9       Nandu      10  89    45  45  69     46
10  Sai kiran      11  64    69  11  78     63
11  Sai Reddy      12  34    11  78  69     48
12  Srikanth       13  89    45  10  45     22
13    Sathish      14  78    63  45  69     24

In [25]:
df.head() #first 5

     Names  RollNo  AI  DBMS  PP  WP  EMSML
0   Rajesh       1  70    45  43  45     89
1  Mahesh        2  85    56  13  63     78
2   Naresh       3  89    46  46  23     46
3   Suresh       4  92    31  78  15     86
4   Vishnu       5  94    30  23  46     79

In [26]:
df.tail() #Last 5

        Names  RollNo  AI  DBMS  PP  WP  EMSML
9       Nandu      10  89    45  45  69     46
10  Sai kiran      11  64    69  11  78     63
11  Sai Reddy      12  34    11  78  69     48
12  Srikanth       13  89    45  10  45     22
13    Sathish      14  78    63  45  69     24

In [27]:
df.shape  #(rows,cols)

(14, 7)

In [28]:
df.columns

Index(['Names', 'RollNo', 'AI', 'DBMS', 'PP', 'WP', 'EMSML'], dtype='object')

In [29]:
df.info

<bound method DataFrame.info of         Names  RollNo  AI  DBMS  PP  WP  EMSML
0      Rajesh       1  70    45  43  45     89
1     Mahesh        2  85    56  13  63     78
2      Naresh       3  89    46  46  23     46
3      Suresh       4  92    31  78  15     86
4      Vishnu       5  94    30  23  46     79
5     Pradeep       6  87    89  96  75     36
6      Ramesh       7  84    74  45  14     45
7     Amrutha       8  86    26  78  11     21
8    Sai Teja       9  83    89  69  45     25
9       Nandu      10  89    45  45  69     46
10  Sai kiran      11  64    69  11  78     63
11  Sai Reddy      12  34    11  78  69     48
12  Srikanth       13  89    45  10  45     22
13    Sathish      14  78    63  45  69     24>

In [31]:
df.describe() #For only numerical columns

        RollNo         AI       DBMS         PP         WP      EMSML
count  14.0000  14.000000  14.000000  14.000000  14.000000  14.000000
mean    7.5000  80.285714  51.357143  48.571429  47.642857  50.571429
std     4.1833  15.671771  23.381805  27.955223  23.931335  24.478293
min     1.0000  34.000000  11.000000  10.000000  11.000000  21.000000
25%     4.2500  79.250000  34.500000  28.000000  28.500000  27.750000
50%     7.5000  85.500000  45.500000  45.000000  45.500000  46.000000
75%    10.7500  89.000000  67.500000  75.750000  69.000000  74.250000
max    14.0000  94.000000  89.000000  96.000000  78.000000  89.000000

In [32]:
df.isnull()

    Names  RollNo     AI   DBMS     PP     WP  EMSML
0   False   False  False  False  False  False  False
1   False   False  False  False  False  False  False
2   False   False  False  False  False  False  False
3   False   False  False  False  False  False  False
4   False   False  False  False  False  False  False
5   False   False  False  False  False  False  False
6   False   False  False  False  False  False  False
7   False   False  False  False  False  False  False
8   False   False  False  False  False  False  False
9   False   False  False  False  False  False  False
10  False   False  False  False  False  False  False
11  False   False  False  False  False  False  False
12  False   False  False  False  False  False  False
13  False   False  False  False  False  False  False

In [33]:
df.isnull().sum()

Names     0
RollNo    0
AI        0
DBMS      0
PP        0
WP        0
EMSML     0
dtype: int64

In [36]:
#fill the missing values
df['AI']=df['AI'].fillna(df['AI'].mean())
print(df)

        Names  RollNo  AI  DBMS  PP  WP  EMSML
0      Rajesh       1  70    45  43  45     89
1     Mahesh        2  85    56  13  63     78
2      Naresh       3  89    46  46  23     46
3      Suresh       4  92    31  78  15     86
4      Vishnu       5  94    30  23  46     79
5     Pradeep       6  87    89  96  75     36
6      Ramesh       7  84    74  45  14     45
7     Amrutha       8  86    26  78  11     21
8    Sai Teja       9  83    89  69  45     25
9       Nandu      10  89    45  45  69     46
10  Sai kiran      11  64    69  11  78     63
11  Sai Reddy      12  34    11  78  69     48
12  Srikanth       13  89    45  10  45     22
13    Sathish      14  78    63  45  69     24

In [37]:
#sorting
df.sort_values('AI',ascending=False)

        Names  RollNo  AI  DBMS  PP  WP  EMSML
4      Vishnu       5  94    30  23  46     79
3      Suresh       4  92    31  78  15     86
2      Naresh       3  89    46  46  23     46
9       Nandu      10  89    45  45  69     46
12  Srikanth       13  89    45  10  45     22
5     Pradeep       6  87    89  96  75     36
7     Amrutha       8  86    26  78  11     21
1     Mahesh        2  85    56  13  63     78
6      Ramesh       7  84    74  45  14     45
8    Sai Teja       9  83    89  69  45     25
13    Sathish      14  78    63  45  69     24
0      Rajesh       1  70    45  43  45     89
10  Sai kiran      11  64    69  11  78     63
11  Sai Reddy      12  34    11  78  69     48

In [38]:
#group by
df['AI']=[90,80,70,50]

ValueError: Length of values (4) does not match length of index (14)

In [39]:
df['AI'].value_counts()

AI
89    3
70    1
85    1
92    1
94    1
87    1
84    1
86    1
83    1
64    1
34    1
78    1
Name: count, dtype: int64